[package]
name = "jpeg-decoder"
version = "0.1.2"
authors = ["Ulf Nilsson <kaksmet@gmail.com>"]
description = "JPEG decoder"
repository = "https://github.com/kaksmet/jpeg-decoder"
readme = "README.md"
keywords = ["JPEG", "decoder", "image"]
license = "MIT / Apache-2.0"

exclude = ["tests/*"]

[dependencies]
byteorder = "0.4"
euclid = "0.6"
rayon = "0.3"

[dependencies.num]
version = "0.1.25"
default-features = false
features = ["rational"]

[dev-dependencies]
walkdir = "0.1"
png = "0.4.1"
